<?php

namespace Database\Seeders\Tools\SSCT;

use App\Models\PsikotesQuestion;
use App\Models\PsikotesTool;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SsctQuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ssct = PsikotesTool::where('name', 'SSCT')->with('sections')->first();

        $questions = [
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 1,
                'type' => 'essay',
                'text' => 'Saya merasa bahwa Ayah saya jarang ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 2,
                'type' => 'essay',
                'text' => 'Bila keadaan tidak menguntungkan bagi saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 3,
                'type' => 'essay',
                'text' => 'Saya selalu mempunyai keinginan untuk ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 4,
                'type' => 'essay',
                'text' => 'Umpamanya saya ditugaskan untuk ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 5,
                'type' => 'essay',
                'text' => 'Bagi saya hari depan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 6,
                'type' => 'essay',
                'text' => 'Orang-orang di atas saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 7,
                'type' => 'essay',
                'text' => 'Saya sadar bahwa hal tersebut janggal tetapi saya takut akan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 8,
                'type' => 'essay',
                'text' => 'Saya merasa bahwa seorang teman sejati ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 9,
                'type' => 'essay',
                'text' => 'Waktu saya masih kecil ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 10,
                'type' => 'essay',
                'text' => 'Saya gambarkan sebagai seorang wanita yang sempurna ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 11,
                'type' => 'essay',
                'text' => 'Bila saya melihat seorang wanita dan lelaki bersama-sama ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 12,
                'type' => 'essay',
                'text' => 'Dibandingkan dengan kebanyakan keluarga, keluarga saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 13,
                'type' => 'essay',
                'text' => 'Di tempat kerja saya, saya paling cocok dengan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 14,
                'type' => 'essay',
                'text' => 'Ibu saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 15,
                'type' => 'essay',
                'text' => 'Saya mau berbuat apa saja untuk melupakan waktu di mana saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 16,
                'type' => 'essay',
                'text' => 'Sekiranya Ayah saya sudi ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 17,
                'type' => 'essay',
                'text' => 'Saya yakin bahwa saya mempunyai kemampuan untuk ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 18,
                'type' => 'essay',
                'text' => 'Saya dapat merasa betul-betul senang kalau ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 19,
                'type' => 'essay',
                'text' => 'Bila orang kerja untuk saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 20,
                'type' => 'essay',
                'text' => 'Saya menantikan dengan penuh harapan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 21,
                'type' => 'essay',
                'text' => 'Di sekolah guru-guru saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 22,
                'type' => 'essay',
                'text' => 'Kebanyakan teman-teman tidak mengetahui bahwa saya takut akan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 23,
                'type' => 'essay',
                'text' => 'Saya tidak senang kepada orang yang ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 24,
                'type' => 'essay',
                'text' => 'Dahulu saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 25,
                'type' => 'essay',
                'text' => 'Saya kira kebanyakan anak perempuan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 26,
                'type' => 'essay',
                'text' => 'Perasaan saya mengenai kehidupan perkawinan adalah ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 27,
                'type' => 'essay',
                'text' => 'Keluarga saya memperlakukan saya sebagai ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 28,
                'type' => 'essay',
                'text' => 'Teman-teman sekerja saya adalah ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 29,
                'type' => 'essay',
                'text' => 'Ibu saya dan saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 30,
                'type' => 'essay',
                'text' => 'Kesalahan saya yang terbesar adalah ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 31,
                'type' => 'essay',
                'text' => 'Saya ingin Ayah saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 32,
                'type' => 'essay',
                'text' => 'Kelemahan saya yang terbesar adalah ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 33,
                'type' => 'essay',
                'text' => 'Hasrat keinginan saya yang terpendam dalam hidup adalah ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 34,
                'type' => 'essay',
                'text' => 'Orang-orang yang bekerja untuk saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 35,
                'type' => 'essay',
                'text' => 'Pada suatu hari saya akan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 36,
                'type' => 'essay',
                'text' => 'Bila saya melihat majikan saya datang ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 37,
                'type' => 'essay',
                'text' => 'Saya akan menghilangkan ketakutan saya akan ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 38,
                'type' => 'essay',
                'text' => 'Orang-orang yang paling saya sukai ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 39,
                'type' => 'essay',
                'text' => 'Andaikata saya muda kembali ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 40,
                'type' => 'essay',
                'text' => 'Saya percaya kebanyakan wanita ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 41,
                'type' => 'essay',
                'text' => 'Umpamakan saya mempunyai hubungan seksual ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 42,
                'type' => 'essay',
                'text' => 'Kebanyakan keluarga yang saya kenal ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 43,
                'type' => 'essay',
                'text' => 'Saya senang bekerja dengan orang yang ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 44,
                'type' => 'essay',
                'text' => 'Saya kira kebanyakan Ibu ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 45,
                'type' => 'essay',
                'text' => 'Waktu saya masih muda, saya merasa berdosa mengenai ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 46,
                'type' => 'essay',
                'text' => 'Saya merasa bahwa Ayah saya adalah ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 47,
                'type' => 'essay',
                'text' => 'Bila mengalami nasib malang ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 48,
                'type' => 'essay',
                'text' => 'Dalam memberikan perintah pada orang lain saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 49,
                'type' => 'essay',
                'text' => 'Yang paling saya inginkan dari hidup ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 50,
                'type' => 'essay',
                'text' => 'Bila saya sudah lebih tua ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 51,
                'type' => 'essay',
                'text' => 'Orang-orang yang saya anggap sebagai atasan saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 52,
                'type' => 'essay',
                'text' => 'Rasa ketakutan kadang-kadang memaksa saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 53,
                'type' => 'essay',
                'text' => 'Bila saya tidak ada, teman-teman saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 54,
                'type' => 'essay',
                'text' => 'Kenangan yang paling jelas dalam hidup dari masa kanak-kanak ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 55,
                'type' => 'essay',
                'text' => 'Yang paling tidak saya sukai mengenai wanita ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 56,
                'type' => 'essay',
                'text' => 'Kehidupan seksual saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 57,
                'type' => 'essay',
                'text' => 'Waktu saya masih seorang anak, keluarga saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 58,
                'type' => 'essay',
                'text' => 'Orang-orang yang bekerja dengan saya ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 59,
                'type' => 'essay',
                'text' => 'Saya suka kepada Ibu saya tetapi ...',
                'options' => [],
                'scoring' => [],
            ],
            [
                'psikotes_section_id' => $ssct->sections[0]->id,
                'order' => 60,
                'type' => 'essay',
                'text' => 'Hal terburuk yang pernah saya lakukan ...',
                'options' => [],
                'scoring' => [],
            ],
        ];

        foreach ($questions as $question) {
            PsikotesQuestion::create($question);
        }
    }
}
